# RENAME FILE TO 'config.yml'
bot:
  token: OTU4MjE4NzM3NTk5ODA3NTM4.YkKIvQ.Ba6kAWs3S9FAHf4lPF5ElsoS_bY
  owner_ids:
    - 958218737599807538
  prefix: $
  default_bet: 100
  bonus_multiplier: 5 # bonus = default_bet * multiplier
  bonus_cooldown: 12 # Bonus every x hours
